import type { Decorator } from '@storybook/react';
import { AppDataContext } from '../src/app/context/AppDataContext';

export const withMockAppData: Decorator = (Story) => (
  <AppDataContext.Provider value={{
    currentUser: { id: 'mock-user', handle: 'testuser', display_name: 'Test User', profile_picture: null },
    session: { user: { id: 'mock-user' } },
    isAuthenticated: true,
    isLoading: false,
    isRefreshing: false,
    topicPostsReady: true,
    hasUnreadNotifications: false,
    unreadNotificationCount: 0,
    users: [],
    posts: [],
    groups: [],
    likedPosts: new Set(),
    repostedPosts: new Set(),
    blockedUsers: new Set(),
    mutedUsers: new Set(),
    followingIds: new Set(),
    followedGameIds: new Set(),
    filteredSocialPlatforms: new Set(),
    externalFollowIds: new Set(),
    savedPostIds: new Set(),
    vipListIds: new Set(),
    signIn: async () => {},
    signUp: async () => {},
    signInWithGoogle: async () => {},
    signOut: async () => {},
    updateCurrentUser: async () => {},
    createPost: async () => undefined,
    addPosts: () => {},
    deletePost: async () => {},
    likePost: async () => {},
    unlikePost: async () => {},
    repostPost: async () => {},
    unrepostPost: async () => {},
    followUser: async () => {},
    unfollowUser: async () => {},
    blockUser: async () => {},
    unblockUser: async () => {},
    muteUser: async () => {},
    unmuteUser: async () => {},
    toggleSocialPlatformFilter: () => {},
    getUserById: () => undefined,
    getUserByHandle: () => undefined,
    updateGameList: async () => {},
    createGroup: async () => ({}),
    refreshFeed: async () => ({ posts: [], groups: [] }),
    refreshFeedPosts: async () => {},
    refreshGroups: async () => {},
    markNotificationsAsRead: () => {},
    followGame: async () => {},
    unfollowGame: async () => {},
    followExternalUser: async () => {},
    unfollowExternalUser: async () => {},
    refreshCurrentUser: async () => {},
    savePost: async () => {},
    unsavePost: async () => {},
    addToVIPList: async () => {},
    removeFromVIPList: async () => {},
  } as any}>
    <Story />
  </AppDataContext.Provider>
);
